# Generated by Django 2.2.7 on 2019-11-24 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sighting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=20, max_digits=20)),
                ('longitude', models.DecimalField(decimal_places=20, max_digits=20)),
                ('shift', models.CharField(blank=True, choices=[('AM', 'AM'), ('PM', 'PM')], default='', help_text='Time of sighting', max_length=2)),
                ('_date', models.DateTimeField(verbose_name='date sighted')),
            ],
        ),
    ]
