# Generated by Django 2.2.7 on 2019-11-29 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20191128_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='latitude',
            field=models.DecimalField(decimal_places=25, max_digits=35),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='longitude',
            field=models.DecimalField(decimal_places=25, max_digits=35),
        ),
    ]
