# Generated by Django 2.2.7 on 2019-11-29 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20191128_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='unique_squirrel_id',
            field=models.SlugField(blank=True, default=''),
        ),
    ]
