# Generated by Django 2.2.7 on 2019-11-29 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_auto_20191128_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='other_activites',
            field=models.TextField(blank=True, default=''),
        ),
    ]
