# Generated by Django 2.2.7 on 2019-11-29 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_auto_20191129_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sighting',
            old_name='other_activites',
            new_name='other_activities',
        ),
    ]
