# Generated by Django 3.0 on 2019-12-03 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_auto_20191129_1457'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sighting',
            options={'get_latest_by': ['date']},
        ),
    ]
