# Generated by Django 3.0 on 2019-12-03 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_auto_20191203_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='unique_squirrel_id',
            field=models.SlugField(blank=True, default='', unique=True),
        ),
    ]
