# Generated by Django 3.0 on 2019-12-07 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_auto_20191203_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='approaches',
            field=models.BooleanField(default=False, help_text='Did the squirrel approach you?'),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='chasing',
            field=models.BooleanField(default=False, help_text='Is the squirrel chasing?'),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='climbing',
            field=models.BooleanField(default=False, help_text='Is the squirrel climbing?'),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='eating',
            field=models.BooleanField(default=False, help_text='Is the squirrel eating?'),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='foraging',
            field=models.BooleanField(default=False, help_text='Is the squirrel foraging?'),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='indifferent',
            field=models.BooleanField(default=False, help_text='Was the squirrel indifferent to you?'),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='kuks',
            field=models.BooleanField(default=False, help_text='Is the squirrel kuking?'),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='moans',
            field=models.BooleanField(default=False, help_text='Is the squirrel moaning?'),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='other_activities',
            field=models.TextField(blank=True, default='', help_text='What other activites is the squirrel doing?'),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='quaas',
            field=models.BooleanField(default=False, help_text='Is the squirrel quaaing?'),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='running',
            field=models.BooleanField(default=False, help_text='Is the squirrel running?'),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='runs_from',
            field=models.BooleanField(default=False, help_text='Did the squirrel run from you?'),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='specific_location',
            field=models.CharField(blank=True, default='', help_text='Specific location of the sighting', max_length=255),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='tail_flags',
            field=models.BooleanField(default=False, help_text='Does the squirrel have a tail flag?'),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='tail_twitches',
            field=models.BooleanField(default=False, help_text="Is the squirrel's tail twitching?"),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='unique_squirrel_id',
            field=models.SlugField(default='', unique=True),
        ),
    ]
